# Generated by Django 5.2.1 on 2025-05-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together={('name', 'address')},
        ),
    ]
