# Generated by Django 5.2 on 2025-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(default='', upload_to='static/workshops'),
        ),
    ]
