# Generated by Django 5.2 on 2025-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(default='', upload_to='static/workshops'),
        ),
    ]
