# Generated by Django 5.2.1 on 2025-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='club',
        ),
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
