# Generated by Django 5.2.1 on 2025-05-19 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0002_remove_locations_club_locations_lat_locations_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_mins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_traffic_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='project_content.locations')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='project_content.locations')),
            ],
        ),
    ]
