# Generated by Django 5.2.1 on 2025-05-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'price', 'description')},
        ),
    ]
